//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloWorldMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public string FirstName { get; set; }
        public int TimesMet { get; set; }
        public Nullable<System.DateTime> DateMet { get; set; }
    }
}
